const ActionTypes = {
  REST_LOADING: "REST_LOADING",
  REST_SUCCESS: "REST_SUCCESS",
  REST_ERROR: "REST_ERROR",
  CART_LOADING: "CART_LOADING",
  CART_SUCCESS: "CART_SUCCESS",
  CART_ERROR: "CART_ERROR",
};

export default ActionTypes;
